config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#index'
  get 'bracelets/:id', to: 'bracelets#show'
  get 'bracelets/index', to: 'bracelets#index'
  get 'students', to: 'students#index'
  get "students/:id", to: "students#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bracelet.rb
class Bracelet < ApplicationRecord
  has_one_attached :photo
end

app/models/student.rb
class Student < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bracelets_controller.rb
class BraceletsController < ApplicationController
  def index
    @bracelets = Bracelet.all
  end

  def show
    @bracelet = Bracelet.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @students = Student.all
    @bracelets = Bracelet.all
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bracelets_helper.rb
module BraceletsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/bracelets/index.html.erb
<% @bracelets.each do |bracelet| %>
  <h2><%= bracelet.name %></h2>
  <p><%= bracelet.price %></p>
  <p><%= bracelet.color %></p>
<% end %>
<%= cl_image_tag("red_bracelet",
      width: 400, height: 300, crop: :fill) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DiyKodulehtVivita</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <p></p>
  </body>
</html>

app/views/pages/index.html.erb
<% @bracelets.each do |bracelet| %>
  <h2><%= bracelet.name %></h2>
  <p><%= bracelet.price %></p>
  <p><%= bracelet.color %></p>
<% end %>
<%= cl_image_tag("red_bracelet",
      width: 400, height: 300, crop: :fill) %>

<%= cl_image_tag("vera",
      width: 400, height: 300, crop: :fill) %>
<br>


<% @students.each do |student| %>
  <%= link_to student.name, students_path(student) %>
  <p><%= student.age %></p>
<% end %>

app/views/students/index.html.erb
<% @students.each do |student| %>
  <%= link_to student.name, students_path(student) %>
  <p><%= student.age %></p>
<% end %>

app/views/students/show.html.erb
<h1><%= @student.name %></h1>
<p></p>